sudo: required
services: 
  - docker
before_install:
  - docker build -t skrfrontend/frontend -f Dockerfile.dev .

script:
  - docker run -e CI=true skrfrontend/frontend npm run test

language: generic

deploy: 
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker"
  env: "DockerReact-env-1"
  bucket_name: "elasticbeanstalk-us-east-1-543847078269"
  bucket_path: "docker"
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: "$AWS_SECRET_KEY"
  on:
    branch: master